# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

xcversion(version: "15.2")

default_platform(:ios)

platform :ios do
  before_all do
    setup_ci
  end
  desc "Description of what the lane does"

  lane :testandbuild do
    match(type:  "adhoc", readonly: is_ci, force_for_new_devices: true,
    app_identifier: ENV["APP_ID"])
    gym(export_method: "ad-hoc", scheme: "AwesomeProject")
  end


end
